<a href="https://colab.research.google.com/github/jhwnoh/UST-GenerativeModels/blob/master/GAN_with_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [1] Practice of GAN with MNIST dataset

Code reference: https://github.com/lyeoni/pytorch-mnist-GAN/tree/master

Import packages required in this practics

In [9]:
# prerequisites
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
from torchvision.utils import save_image

import numpy as np
from tqdm import tqdm

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

Download MNIST dataset

In [2]:
bs = 100 # batch size

# MNIST Dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5,), std=(0.5,))]) #preprocess function

train_dataset = datasets.MNIST(root='./mnist_data/', train=True, transform=transform, download=True)
test_dataset = datasets.MNIST(root='./mnist_data/', train=False, transform=transform, download=False)

# Data Loader (Input Pipeline)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=bs, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=bs, shuffle=False)

100%|██████████| 9912422/9912422 [00:00<00:00, 87126481.06it/s]


Extracting ./mnist_data/MNIST/raw/train-images-idx3-ubyte.gz to ./mnist_data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 75899557.53it/s]


Extracting ./mnist_data/MNIST/raw/train-labels-idx1-ubyte.gz to ./mnist_data/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 21038019.90it/s]


Extracting ./mnist_data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./mnist_data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 15350949.85it/s]


Extracting ./mnist_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./mnist_data/MNIST/raw



Define neural networks (Generator and Discriminator)
- Generator: converting z to x
- Discrimiator: predict the given x is obtained from the data distribution or generator

In [3]:
class Generator(nn.Module):
    def __init__(self, g_input_dim, g_output_dim):
        super(Generator, self).__init__()
        self.fc1 = nn.Linear(g_input_dim, 256)
        self.fc2 = nn.Linear(self.fc1.out_features, self.fc1.out_features*2)
        self.fc3 = nn.Linear(self.fc2.out_features, self.fc2.out_features*2)
        self.fc4 = nn.Linear(self.fc3.out_features, g_output_dim)

    # forward method
    def forward(self, x):
        x = F.leaky_relu(self.fc1(x), 0.2)
        x = F.leaky_relu(self.fc2(x), 0.2)
        x = F.leaky_relu(self.fc3(x), 0.2)
        return torch.tanh(self.fc4(x))

class Discriminator(nn.Module):
    def __init__(self, d_input_dim):
        super(Discriminator, self).__init__()
        self.fc1 = nn.Linear(d_input_dim, 1024)
        self.fc2 = nn.Linear(self.fc1.out_features, self.fc1.out_features//2)
        self.fc3 = nn.Linear(self.fc2.out_features, self.fc2.out_features//2)
        self.fc4 = nn.Linear(self.fc3.out_features, 1)

    # forward method
    def forward(self, x):
        x = F.leaky_relu(self.fc1(x), 0.2)
        x = F.dropout(x, 0.3)
        x = F.leaky_relu(self.fc2(x), 0.2)
        x = F.dropout(x, 0.3)
        x = F.leaky_relu(self.fc3(x), 0.2)
        x = F.dropout(x, 0.3)
        return torch.sigmoid(self.fc4(x))

In [4]:
# build network
z_dim = 128
mnist_dim = 28*28

G = Generator(g_input_dim = z_dim, g_output_dim = mnist_dim).to(device)
D = Discriminator(mnist_dim).to(device)

print(G)
print(D)

Generator(
  (fc1): Linear(in_features=128, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=1024, bias=True)
  (fc4): Linear(in_features=1024, out_features=784, bias=True)
)
Discriminator(
  (fc1): Linear(in_features=784, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (fc4): Linear(in_features=256, out_features=1, bias=True)
)


In [5]:
# loss
criterion = nn.BCELoss()

# optimizer
lr = 0.0002
G_optimizer = optim.Adam(G.parameters(), lr = lr)
D_optimizer = optim.Adam(D.parameters(), lr = lr)

In [6]:
def D_train(x):
    #=======================Train the discriminator=======================#
    D.zero_grad()

    # train discriminator on real
    x_real, y_real = x.view(-1, mnist_dim), torch.ones(bs, 1)
    x_real, y_real = Variable(x_real.to(device)), Variable(y_real.to(device))

    D_output = D(x_real)
    D_real_loss = criterion(D_output, y_real)
    D_real_score = D_output
    N_d1 = torch.sum(D_output>=0.5)

    # train discriminator on facke
    z = Variable(torch.randn(bs, z_dim).to(device))
    x_fake, y_fake = G(0.3*z), Variable(torch.zeros(bs, 1).to(device))

    D_output = D(x_fake)
    D_fake_loss = criterion(D_output, y_fake)
    D_fake_score = D_output
    N_d2 = torch.sum(D_output>=0.5)

    # gradient backprop & optimize ONLY D's parameters
    D_loss = D_real_loss + D_fake_loss
    D_loss.backward()
    D_optimizer.step()

    return  D_loss.data.item(),N_d1.data.item(),N_d2.data.item()

In [7]:
def G_train(x):
    #=======================Train the generator=======================#
    G.zero_grad()

    z = Variable(torch.randn(bs, z_dim).to(device))
    y = Variable(torch.ones(bs, 1).to(device))

    G_output = G(0.3*z)
    D_output = D(G_output)
    G_loss = criterion(D_output, y)
    N_g = torch.sum(D_output>=0.5)

    # gradient backprop & optimize ONLY G's parameters
    G_loss.backward()
    G_optimizer.step()

    return G_loss.data.item(),N_g.data.item()

In [10]:
Ntr = len(train_dataset)

n_epoch = 200
for epoch in range(1, n_epoch+1):
    D_losses, G_losses = [], []
    Ns = []
    for x, _ in tqdm(train_loader):
        l_d,n_d1,n_d2 = D_train(x)
        l_g,n_g = G_train(x)

        D_losses.append(l_d)
        G_losses.append(l_g)
        Ns.append([n_d1,n_d2,n_g])

    Ns = np.array(Ns)

    print('[%d/%d]: loss_d: %.3f, loss_g: %.3f' % (
            (epoch), n_epoch, torch.mean(torch.FloatTensor(D_losses)), torch.mean(torch.FloatTensor(G_losses))))
    print(np.sum(Ns,0)/Ntr)

    if True:
        G.eval()

        with torch.no_grad():
            test_z = Variable(torch.randn(bs, z_dim).to(device))
            generated = G(0.3*test_z).cpu().detach().numpy()
            save_image(generated.view(generated.size(0), 1, 28, 28), './sample_gan_'+ str(epoch) + '.png')

        G.train()


100%|██████████| 600/600 [01:28<00:00,  6.78it/s]


[1/200]: loss_d: 0.979, loss_g: 1.814
[0.80778333 0.27293333 0.16068333]


 44%|████▎     | 262/600 [00:39<00:51,  6.58it/s]


KeyboardInterrupt: ignored

# [2] Practice of DCGAN with MNIST dataset

In [11]:
# prerequisites
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
from torchvision.utils import save_image

import numpy as np
from tqdm import tqdm

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [12]:
bs = 100 # batch size

# MNIST Dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5,), std=(0.5,))]) #preprocess function

train_dataset = datasets.MNIST(root='./mnist_data/', train=True, transform=transform, download=True)
test_dataset = datasets.MNIST(root='./mnist_data/', train=False, transform=transform, download=False)

# Data Loader (Input Pipeline)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=bs, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=bs, shuffle=False)

In [13]:
# custom weights initialization called on netG and netD
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        m.weight.data.normal_(0.0, 0.02)
    elif classname.find('BatchNorm') != -1:
        m.weight.data.normal_(1.0, 0.02)
        m.bias.data.fill_(0)

In [14]:
class Generator(nn.Module):
    def __init__(self, ngpu=1, nc=1, nz=100, ngf=64):
        super(Generator, self).__init__()
        self.ngpu = ngpu
        self.main = nn.Sequential(
            # input is Z, going into a convolution
            nn.ConvTranspose2d(     nz, ngf * 8, 4, 1, 0, bias=False),
            nn.BatchNorm2d(ngf * 8),
            nn.ReLU(True),
            # state size. (ngf*8) x 4 x 4
            nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 4),
            nn.ReLU(True),
            # state size. (ngf*4) x 8 x 8
            nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf * 2),
            nn.ReLU(True),
            # state size. (ngf*2) x 16 x 16
            nn.ConvTranspose2d(ngf * 2,     ngf, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ngf),
            nn.ReLU(True),
            nn.ConvTranspose2d(    ngf,      nc, kernel_size=1, stride=1, padding=2, bias=False),
            nn.Tanh()
        )

    def forward(self, input):
        if input.is_cuda and self.ngpu > 1:
            output = nn.parallel.data_parallel(self.main, input, range(self.ngpu))
        else:
            output = self.main(input)
        return output

class Discriminator(nn.Module):
    def __init__(self, ngpu=1, nc=1, ndf=64):
        super(Discriminator, self).__init__()
        self.ngpu = ngpu
        self.main = nn.Sequential(
            # input is (nc) x 64 x 64
            nn.Conv2d(nc, ndf, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (ndf) x 32 x 32
            nn.Conv2d(ndf, ndf * 2, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 2),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (ndf*2) x 16 x 16
            nn.Conv2d(ndf * 2, ndf * 4, 4, 2, 1, bias=False),
            nn.BatchNorm2d(ndf * 4),
            nn.LeakyReLU(0.2, inplace=True),
            # state size. (ndf*4) x 8 x 8
            nn.Conv2d(ndf * 4, 1, 4, 2, 1, bias=False),
            nn.Sigmoid()
        )

    def forward(self, input):
        if input.is_cuda and self.ngpu > 1:
            output = nn.parallel.data_parallel(self.main, input, range(self.ngpu))
        else:
            output = self.main(input)
        return output.view(-1, 1)

In [18]:
# build network
z_dim = 100
mnist_dim = 28*28

G = Generator(nz = z_dim,ngf=4).to(device)
G.apply(weights_init)

D = Discriminator(ndf=4).to(device)
D.apply(weights_init)

# loss
criterion = nn.BCELoss()

# optimizer
lr = 0.0002
G_optimizer = optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.999))
D_optimizer = optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.999))

def D_train(x):
    #=======================Train the discriminator=======================#
    D.zero_grad()

    # train discriminator on real
    x_real, y_real = x, torch.ones(bs, 1)
    x_real, y_real = Variable(x_real.to(device)), Variable(y_real.to(device))

    D_output = D(x_real)
    D_real_loss = criterion(D_output, y_real)
    D_real_score = D_output
    N_d1 = torch.sum(D_output>=0.5)

    # train discriminator on facke
    z = Variable(torch.randn(bs, z_dim, 1, 1).to(device))
    x_fake, y_fake = G(0.3*z), Variable(torch.zeros(bs, 1).to(device))

    D_output = D(x_fake)
    D_fake_loss = criterion(D_output, y_fake)
    D_fake_score = D_output
    N_d2 = torch.sum(D_output>=0.5)

    # gradient backprop & optimize ONLY D's parameters
    D_loss = D_real_loss + D_fake_loss
    D_loss.backward()
    D_optimizer.step()

    return  D_loss.data.item(),N_d1.data.item(),N_d2.data.item()

def G_train(x):
    #=======================Train the generator=======================#
    G.zero_grad()

    z = Variable(torch.randn(bs, z_dim, 1, 1).to(device))
    y = Variable(torch.ones(bs, 1).to(device))

    G_output = G(0.3*z)
    D_output = D(G_output)
    G_loss = criterion(D_output, y)
    N_g = torch.sum(D_output>=0.5)

    # gradient backprop & optimize ONLY G's parameters
    G_loss.backward()
    G_optimizer.step()

    return G_loss.data.item(),N_g.data.item()

In [19]:
Ntr = len(train_dataset)

n_epoch = 50
for epoch in range(1, n_epoch+1):
    D_losses, G_losses = [], []
    Ns = []
    for x, _ in tqdm(train_loader):
        l_d,n_d1,n_d2 = D_train(x)
        l_g,n_g = G_train(x)

        D_losses.append(l_d)
        G_losses.append(l_g)
        Ns.append([n_d1,n_d2,n_g])

    Ns = np.array(Ns)

    print('[%d/%d]: loss_d: %.3f, loss_g: %.3f' % (
            (epoch), n_epoch, torch.mean(torch.FloatTensor(D_losses)), torch.mean(torch.FloatTensor(G_losses))))
    print(np.sum(Ns,0)/Ntr)

    if True:

        G.eval()

        with torch.no_grad():
            test_z = Variable(torch.randn(bs, z_dim,1,1).to(device))
            generated = G(0.3*test_z)
            save_image(generated.view(generated.size(0), 1, 28, 28), './sample_dcgan_'+ str(epoch) + '.png')

        #res = {'G':G.state_dict(),'D':D.state_dict()}
        #torch.save(res,'param_dcgan.'+str(epoch)+'.pth.tar')
        G.train()

100%|██████████| 600/600 [01:05<00:00,  9.10it/s]


[1/50]: loss_d: 0.331, loss_g: 2.554
[0.99728333 0.12451667 0.10985   ]


100%|██████████| 600/600 [01:06<00:00,  9.02it/s]


[2/50]: loss_d: 0.163, loss_g: 4.345
[0.98108333 0.01721667 0.00893333]


100%|██████████| 600/600 [01:06<00:00,  9.09it/s]


[3/50]: loss_d: 0.468, loss_g: 2.273
[0.93518333 0.05288333 0.04228333]


100%|██████████| 600/600 [01:06<00:00,  9.05it/s]


[4/50]: loss_d: 0.739, loss_g: 1.524
[0.86418333 0.11798333 0.10953333]


100%|██████████| 600/600 [01:06<00:00,  9.03it/s]


[5/50]: loss_d: 0.913, loss_g: 1.228
[0.81266667 0.16928333 0.15301667]


100%|██████████| 600/600 [01:10<00:00,  8.47it/s]


[6/50]: loss_d: 1.031, loss_g: 1.070
[0.76665    0.21551667 0.20295   ]


100%|██████████| 600/600 [01:07<00:00,  8.86it/s]


[7/50]: loss_d: 1.089, loss_g: 0.995
[0.74633333 0.237      0.22776667]


100%|██████████| 600/600 [01:08<00:00,  8.75it/s]


[8/50]: loss_d: 1.156, loss_g: 0.932
[0.71156667 0.2711     0.25961667]


100%|██████████| 600/600 [01:08<00:00,  8.82it/s]


[9/50]: loss_d: 1.197, loss_g: 0.898
[0.68978333 0.30413333 0.29186667]


 61%|██████    | 364/600 [00:40<00:26,  8.89it/s]


KeyboardInterrupt: ignored